### ISSUE TITLE
Destroy Method

### ISSUE THREAD

**Issue by maimairel** [abpetkov/switchery#33]
Hi, great plugin :)

What I'm missing right now is the functionality to destroy a switchery instance. Is it enough to just remove the DOM element, or does such a functionality already exists?

Thank you!

**Comment by abpetkov** [comment]
@maimairel I think <a href="http://stackoverflow.com/questions/10826046/how-to-have-an-instance-delete-itself-from-within-a-prototype-function-is-javasc">that post</a> and it's accepted answer pretty much sums up that it's enough to set all the instances to `null` and probably delete the DOM object to get rid of the instance, instead of trying to really delete it, which appears to be impossible.

**Comment by maimairel** [comment]
@abpetkov Yes, setting it to null or undefined will make the object a candidate for garbage collection, but we need a destroy method to be sure that all event handlers bound by the plugin are removed, otherwise it won't be garbage collected.

**Comment by abpetkov** [comment]
@maimairel I will make a new release until the end of the week, but I've pushed some changes to the master branch. Some of them include the `.destroy()` method you can use on the object reference to unbind all events attached to it. Please take a look if possible and LMK what you think.

**Comment by abpetkov** [comment]
Released in <a href="https://github.com/abpetkov/switchery/releases/tag/0.8.0">0.8.0</a>
